### ISSUE TITLE
@playwright/test/lib/test/globals export doesn't exist in the latest Playwright Test version

### ISSUE THREAD

**Issue by z0n** [florianbepunkt/playwright-image-snapshot#1]
Hi, I'm trying to use this and it seems like it's not working on newer Playwright versions (I'm using Playwright Test 1.16.3).  
The required `globals.js` file is now in `@playwright/test/lib/globals` instead of `@playwright/test/lib/test/globals`. Also, @playwright/test doesn't export `lib/globals` so it won't work without a modified @playwright/test package.  
For testing, I added `"./lib/globals": "./lib/globals.js"` to the exports in the @playwright/test package.json file and it works when combining it with the updated path in `match-image-snapshot.ts`:
https://github.com/florianbepunkt/playwright-image-snapshot/blob/73902670dffb0f734cba0f9e3bf538242a16af71/src/match-image-snapshot.ts#L4

Is this intended to be used with an unmodified Playwright Test? If yes, we should ask them to export `lib/globals`.

**Comment by florianbepunkt** [comment]
I asked them. Don't have the relevant issue at hand atm, but I filed a request. Haven't had a chance to test this project with the current playwright version, but hopefully this package soon will be obsolete, when Playwright improves their own screenshot matcher to include blurring.
